version: '3.8'
services:
  app:
    container_name: metatrader
    image: lucaorioli/metatrader5:current
    restart: unless-stopped
    ports:
      - '15231:5900'
      - '15555:15555'
      - '15556:15556'
      - '15557:15557'
      - '15558:15558'
    volumes:
      - ./data:/data
      - ./Metatrader:/root/Metatrader
    environment:
      - PW_VNC=default_pw_vnc
    networks:
      mynetwork:
        ipv4_address: 172.19.0.2

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.19.0.0/16
